### ISSUE TITLE
სჭირდება requirements.txt ფაილი

### ISSUE THREAD

**Issue by DavidTbilisi** [amiridzegiga/Vaccination-API#1]
pip freeze > requirements.txt

**Comment by amiridzegiga** [comment]
გამარჯობა დავით. requirements ფაილი მაქვს და ტერმინალში მაგას რომ ვუშვებ
ფაილში არ ამატებს არაფერს. ეგ არ არის ჩემი საფინალო პროექტის რეპოზიტორია.
ეს არის: https://github.com/amiridzegiga/Vaccine-API

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
